### ISSUE TITLE
Instalación de dependecias y entorno de trabajo.

### ISSUE THREAD

**Issue by ImaginarioColectivo** [ImaginarioColectivo/PhotoFilter#2]

**Comment by ImaginarioColectivo** [comment]
_hacer eslint @MrsPepa 
_ hacer package.json

**Comment by MrsPepa** [comment]
ya cree archivo package.JSON y eslint

**Comment by ImaginarioColectivo** [comment]
Tarea: Crear primera versión de Read me, incluyendo descripción general y uso de la misma. 
Asignado a: @camilufer

**Comment by ImaginarioColectivo** [comment]
Tarea: Crear primera versión de Read me, incluyendo descripción general y uso de la misma.

**Comment by ImaginarioColectivo** [comment]
Tarea: Crear primera versión de Read me, incluyendo descripción general y uso de la misma. 
Asignada a @camilufer

**Comment by ImaginarioColectivo** [comment]
Agregar al proyecto un archivo .editorconfig con los estilos de código que vamos a utilizar. 
Asiganda a Majo,

**Comment by ImaginarioColectivo** [comment]
Todas las integrantes del equipo instalar Babel para transpilar el código.
Asignada a todas las integrantes del equipo.
Estado tarea: realizada.

**Comment by ImaginarioColectivo** [comment]
Tarea: Creo nueva rama para trabajar el proyecto y al finalizar subir al master.
Estado: realizado.

**Comment by ImaginarioColectivo** [comment]
Tarea: Realización del demo, incluyendo archivo html para visualizar libreria, integrando el estilo con css usando Materialize y el archivo js para implementar funcionalidad a los 11 filtros.
